### PR TITLE
getQueryMock method for more flexiblity.

### PR DESCRIPTION
**Pull request by theorx**
Hi!

I created this method for more flexibility in testing. For example i had to throw an __Exception__ in `$query->getResult()` method and i was unable to pass callback as a parameter to throw new exception in the callback. So as a workaround i had to call `$qbm->getQuery()` and after getting `$mockQueryBuilder` call `$mockQueryBuilder->getQuery()` to get PHPUnit's __mock object__. 

So this method i implemented allows me to get the mockQuery object without mocking getQuery method first. 

Example for the code:

```php
     public function someFunction (){

     ....

      $qb->setParameters($parameters);
	        try {
	            return $qb->getQuery()->getResult();
	        } catch (\Exception $e) {
	            return false;
	        }
    }

```

And the test:

```php

 $qbm = new QueryBuilderMocker($this);
        //$qbm->getQuery here is workaround
        $qbm->getQuery();
 
       ...

        $qbm->setParameters($parameters);
        $qbm->getQuery();
        $qbm = $qbm->getQueryBuilderMock();

        //$mock for workaround
        $mock = $qbm->getQuery();
        /**
         * @var \PHPUnit_Framework_MockObject_MockObject $mock
         */
        $mock->expects($this->once())->method('getResult')->willReturnCallback(function () {

            throw new \Exception;
        });

       // Call the actual method described above
      $object->someFunction();

```

### CODE REVIEW

**Comment by michaelmoussa** [comment]
Merging. Thanks for your contribution!

**Comment by theorx** [comment]
Can you also release new version?

**Comment by michaelmoussa** [comment]
Yup. Working on it as we speak

**Comment by michaelmoussa** [comment]
@theorx done. I did some other minor housekeeping as well so let me know if it causes any issues for you. Thanks again!

**Pull request merged**
